# Generated by Django 2.0 on 2018-01-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publickey',
            old_name='n_val',
            new_name='p_val',
        ),
        migrations.AddField(
            model_name='publickey',
            name='q_val',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
