# Generated by Django 2.0 on 2018-01-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseportal', '0002_auto_20180122_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickey',
            name='publickey',
        ),
    ]
